name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'cfpa'

      - name: force sync
        id: fs
        run: |
          git remote add upstream https://github.com/CFPAOrg/Minecraft-Mod-Language-Package.git
          git fetch upstream main
          git fetch origin cfpa
          git reset --hard upstream/main
          # 有输出则说明有更新, 后续步骤需要推送然后提交pr
          git diff --quiet origin/cfpa || hasDiff=true
          echo "hasDiff="$hasDiff >> $GITHUB_OUTPUT
          echo "hasDiff="$hasDiff

      - name: push
        if: steps.fs.outputs.hasDiff == 'true'
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git push origin cfpa

      - if: steps.fs.outputs.hasDiff == 'true'
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: cfpa
          title: Sync by ci from cfpa
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.fs.outputs.hasDiff == 'true' && steps.pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: merge
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}
