name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: force sync
        id: fs
        run: |
          git remote add upstream https://github.com/CFPAOrg/Minecraft-Mod-Language-Package.git
          git fetch upstream main
          git checkout -b cfpa upstream/main
          git config user.name github-actions
          git config user.email actions@github.com
          git push origin cfpa

      - id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: cfpa/sync
          delete-branch: true
          branch-suffix: timestamp
          title: Sync by ci from cfpa
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: merge
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}
